version: '3.9'

services:
  database:
    build:
      context: .
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
